services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    environment:
      - DB_URL=postgresql+psycopg2://user:password@db:5432/auto_cart
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auto_cart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d auto_cart"]
      interval: 5s
      timeout: 3s
      retries: 12
